name: EconomyLand
version: "1.0.0"
api: [1.0.0]
main: me.onebone.economyland.EconomyLand
author: onebone
depend: [EconomyAPI]

commands:
  land:
    description: "Management command of land"
    usage: "/land <pos1|pos2|buy|sell|give|here|whose|list>"
    permission: economyland.command.land;economyland.command.land.pos1;economyland.command.land.pos2;economyland.command.land.buy;economyland.command.land.sell;economyland.command.land.here;economyland.command.land.whose;economyland.command.land.list;economyland.command.land.move;
permissions:
  economyland:
    description: "Includes all permissions for EconomyLand"
    children:
      economyland.command:
        description: "Allows player to use all commands"
        children:
          economyland.command.land:
            description: "Allows player to use /land"
            default: true
            children:
              economyland.command.land.pos1:
                description: "Allows player to use /land pos1"
              economyland.command.land.pos2:
                description: "Allows player to use /land pos2"
              economyland.command.land.buy:
                description: "Allows player to use /land buy"
              economyland.command.land.sell:
                description: "Allows player to use /land sell"
              economyland.command.land.here:
                description: "Allows player to use /land here"
              economyland.command.land.whose:
                description: "Allows player to use /land whose"
              economyland.command.land.list:
                description: "Allows player to use /land list"
              economyland.command.land.move:
                description: "Allows player to use /land move"
      economyland.buy:
        description: "Allows player to buy land"
        default: true
      economyland.sell:        
        description: "Allows player to sell land"
        default: true
      economyland.admin:
        description: "EconomyLand admin permission"
        children:
          economyland.admin.sell:
            description: "Allows player to sell others' land"
          economyland.admin.modify:
            description: "Allows player to modify others' land"
          economyland.admin.access:
            description: "Allows player to access others' land"
          economyland.admin.pickup:
            description: "Allows player to pick up items in others' land"
 
